{% set name = "fend" %}
{% set version = "1.4.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/printfn/fend/archive/v{{ version }}.tar.gz
  sha256: 5e973bf7f53416039d5efc2f2ec360add5184625644e986808c21e5bd292fc58

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - pandoc
    - pkg-config
  host:
    - openssl

test:
  commands:
    - fend --help

about:
  home: https://printfn.github.io/fend
  license: MIT
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml
  summary: Arbitrary-precision unit-aware calculator
  dev_url: https://github.com/printfn/fend

extra:
  recipe-maintainers:
    - danielnachun
