context:
  version: "1.5.8"

package:
  name: fend
  version: ${{ version }}

source:
  url: https://github.com/printfn/fend/archive/v${{ version }}.tar.gz
  sha256: 2c53922b83b693c852581942ddcf8e02e1bcd691f30c00e8066cdd6ab2070b86

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pandoc
    - pkg-config
  host:
    - openssl

tests:
  - script:
      - fend --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml
  summary: Arbitrary-precision unit-aware calculator
  homepage: https://printfn.github.io/fend
  repository: https://github.com/printfn/fend

extra:
  recipe-maintainers:
    - danielnachun
